export const experience = [
    {
        start: 'Сентябрь 2020',
        end: 'по\xa0настоящее\xa0время',
        duration: '2 года 8 месяцев',
        title: 'Ипотека Центр',
        address: 'ipoteka.center',
        description: 'Старший Frontend-разработчик',
    },
    {
        start: 'Сентябрь 2018',
        end: 'февраль\xa02022',
        duration: '3 года 6 месяцев',
        title: 'Udacity',
        address: 'udacity.com',
        description: 'Старший ментор, Аудитор менторов',
    },
    {
        start: 'Январь 2017',
        end: 'июль\xa02019',
        duration: '2 года 7 месяцев',
        title: 'СОЮЗ, Акционерный Коммерческий Банк',
        address: 'www.banksoyuz.ru',
        description: 'Главный разработчик, Руководитель направления',
    },
    {
        start: 'Март 2016',
        end: 'июль\xa02016',
        duration: '5 месяцев',
        title: 'Diasoft',
        address: 'www.diasoft.ru',
        description: 'Fullstack разработчик',
    },
    {
        start: 'Июнь 2013',
        end: 'октябрь\xa02015',
        duration: '2 года 5 месяцев',
        title: 'ОАО КБ МАСТ Банк',
        address: '',
        description: 'Старший инженер-программист',
    },
    {
        start: 'Сентябрь 2011',
        end: 'май\xa02013',
        duration: '1 год 10 месяцев',
        title: 'Diasoft',
        address: 'www.diasoft.ru',
        description: 'Инженер-программист',
    },
]